pg: print the entire error context
Fixes: #4680

This is what new errors will look like:

```txt
FATAL error on output endpoint 'v1.unnamed-0':
while executing insert statement: [{"id":1}]

Caused by:
    postgres error: permanent: SqlState: Some(SqlState(E23505)): db error:
    ERROR: duplicate key value violates unique constraint "feldera_out_pkey"
    DETAIL: Key (id)=(1) already exists.
```

Signed-off-by: Abhinav Gyawali <22275402+abhizer@users.noreply.github.com>