[adapters] Don't read kafka message 0 if we're not queuing or replaying.
For replay in Kafka, we need to make sure that we only read exactly the
messages in the range to be replayed.  In general, we're pretty good about
this, with one exception: initially, the maximum offset is set to 0
(inclusive).  If the first range of records to be replayed is empty (0..0),
then an initial maximum of 0 will allow in a record anyway.

This commit sets the initial maximum to i64::MIN instead, to fix the
problem.  (-1, or any other negative value, would also work.)

This bug manifested in a failure of the `empty_initial_input` test, e.g.:

```
2025-04-11T16:21:27.9716520Z thread 'transport::kafka::ft::test::empty_initial_input' panicked at crates/adapters/src/transport/kafka/ft/test.rs:240:26:
2025-04-11T16:21:27.9716629Z assertion `left == right` failed
2025-04-11T16:21:27.9716737Z   left: [Replayed { num_records: 0 }]
2025-04-11T16:21:27.9716830Z  right: [Replayed { num_records: 1 }]
```

Signed-off-by: Ben Pfaff <blp@feldera.com>