[adapters] Use `create_new` instead of `create` for marker files.
Fixes a clippy complaint:

```
error: file opened with `create`, but `truncate` behavior not defined
   --> crates/adapters/src/samply.rs:236:14
    |
236 |             .create(true)
    |              ^^^^^^^^^^^^- help: add: `.truncate(true)`
    |
    = help: if you intend to overwrite an existing file entirely, call `.truncate(true)`
    = help: if you instead know that you may want to keep some parts of the old file, call `.truncate(false)`
    = help: alternatively, use `.append(true)` to append to the file instead of overwriting it
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#suspicious_open_options
    = note: `-D clippy::suspicious-open-options` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::suspicious_open_options)]`
```

Signed-off-by: Ben Pfaff <blp@feldera.com>